--creates the Data Base
CREATE DATABASE EMPLOYEE_TRACK;
-- Accessing the Database
USE EMPLOYEE_TRACK;
-- creating tables
CREATE TABLE DEPARTMENT (
 ID INT PRIMARY KEY NOT NULL,
 NAME VARCHAR(30) NOT NULL
);

CREATE TABLE ROLE (
 ID INT PRIMARY KEY NOT NULL,
 TITLE VARCHAR(30) NOT NULL,
 SALARY dECIMAL(6,2) NOT NULL,
 DEPARTMENT_ID INT NOT NULL
);

CREATE TABLE EMPLOYEE (
 ID INT PRIMARY KEY NOT NULL,
 FIRST_NAME VARCHAR(30) NOT NULL,
 LAST_NAME VARCHAR(30) NOT NULL,
 ROLE_ID INT NOT NULL,
 MANAGER_ID INT NOT NULL
);
-- INSERTING DATA INTO THE TABLES
INSERT INTO DEPARTMENT (ID, NAME) VALUE (0, "SOFTWARE ENGINEERING");

INSERT INTO ROLE (ID, TITLE, SALARY, DEPARTMENT_ID) VALUES (0, "ENGINEER", 120.000, 0);

INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, ROLE_ID, MANAGER_ID) VALUES (0, "OSCAR", "NUNEZ", 0, 0);
